### ISSUE TITLE
Refactor FilterForm Value input into separate component

### ISSUE THREAD

**Issue by hextraza** [BimberLab/discvr-components#10]
We have a page that displays data in a table format. You can filter the table using a field + operator + value UI, and you can have multiple filters. An example of a filter for "Allele Frequency > 0.2":

![image](https://github.com/BimberLab/discvr-components/assets/5386960/12f1b929-faa2-4975-8072-d95307657f65)

The rendered JSX for the Value input changes depending on the type of Field you're filtering on. In the vast majority of cases, it's just a simple MUI TextField, like the "Allele Frequency" case. However, for fields with a defined set of possible values, like "Samples With Variant" it'll render a Select:

![image](https://github.com/BimberLab/discvr-components/assets/5386960/c52ba22d-761d-40a0-8904-0ca3a0092ccb)

If there are a lot of possible values, we render a more complex component -- an AsyncSelect from [react-select](https://react-select.com/home):

![image](https://github.com/BimberLab/discvr-components/assets/5386960/0459d84a-fb11-4caf-b281-cce5bb17d719)

The exact specifics vary depending on the Field and Operator. Our goal is to extract these various cases into a component with a clean interface and put it in discvr-components, as an example use-case for our monorepo.

The file containing the filter form is [here](https://github.com/BimberLab/DiscvrLabKeyModules/blob/discvr-23.7/jbrowse/src/client/JBrowse/VariantSearch/components/FilterForm.tsx#L263-L331). The lines that control the Value portion of the form are highlighted. In short:

- We special case the operator "in set", which renders a select field with some special values in it
- If the number of selectable values > 10, we render the complex AsyncSelect
- Otherwise, if the number of selectable values > 0, we render a simple Select
- If there are no selectable values (i.e. we're just accepting any user input) we render a TextField

As you can see, there's a bit of logic behind how we determine which version of the Value input to render. This logic is based on a bunch of external data, i.e. the current filter, the fieldTypeInfo object, and others. In order to refactor this out into a separate component, we need to identify what values we'd need to pass into the component as props in order for all the logic to work. I think the prop list looks like:

- `index`, which refers to the position of this filter in the filter list
- `filter`, so that lines like `filter.operator === "in set"` can work
- `fieldTypeInfo`, for `fieldTypeInfo.find(obj => obj.name === filter.field)?.allowableValues?.length > 10`
- `highlightedInputs`, for the various `highlightedInputs[index]` calls
- `handleFilterChange` for all the onChange callbacks

So, we should produce something that looks like

`const ValueComponent = ({ index, filter, fieldTypeInfo, highlightedInputs, handleFilterChange }) => {<a lot of JSX>}`

such that we can delete the aforementioned lines of code and replace it with this new ValueComponent. We should identify how to test/build this as well.

**Comment by hextraza** [comment]
I added an example implementation [on this branch](https://github.com/BimberLab/DiscvrLabKeyModules/tree/23.7_fb_exampleRefactor).

There's a new component, [ValueInput](https://github.com/BimberLab/DiscvrLabKeyModules/blob/23.7_fb_exampleRefactor/jbrowse/src/client/JBrowse/VariantSearch/components/ValueInput.tsx), that contains all the logic/JSX for the reactive value input stuff we've been talking about. This should be build-able by itself if put in discvr-components. The types/prop interface is a little messy, but it should be a good start. It depends on react, react-select, and MUI.

In the [FilterForm](https://github.com/BimberLab/DiscvrLabKeyModules/blob/23.7_fb_exampleRefactor/jbrowse/src/client/JBrowse/VariantSearch/components/FilterForm.tsx#L258-L265), I've replaced the logic of the value input with a call to the new component.

**Comment by EthanD1998** [comment]
I pretty much have what you have in the ValueInput component. I currently don't have the utils on the the turborepo yet so I don't have filter and fieldModel specified yet. I will probably add that in and change the component to use the props like you have setup.

Currently I am running into an issue with the AsyncSelect not working correctly in JSX. I am getting an error "'AsyncSelect' cannot be used as a JSX component." Would you happen to know anything about this and how I could get it working?
