### ISSUE TITLE
Monorepo management research

### ISSUE THREAD

**Issue by hextraza** [BimberLab/discvr-components#3]
We should research how to do NPM monorepo management. The library I'm aware of to automate this is [Turborepo](https://turbo.build/repo/docs/getting-started/create-new). Evaluate any other options in the space that can be easily deployed and incrementally adopted. A library of some kind is preferable to npm/yarn workspaces. If Turborepo is what we end up going with, you should familiarize yourself with it.

**Comment by EthanD1998** [comment]
Turborepo is what we are going to currently go with. I have started getting Turborepo working in another issue
