### ISSUE TITLE
Push monorepo scaffold

### ISSUE THREAD

**Issue by hextraza** [BimberLab/discvr-components#7]
After determining which framework we want to use per #3, we should push the configuration/code for a monorepo management solution to a feature branch on this repo, with stubs for three packages named the following:

- discvr-utils
- discvr-ui-components
- discvr-jbrowse

These will be empty for now, but later on we'll determine what to pull out of our main repo and put in them.

**Comment by EthanD1998** [comment]
I have just pushed a new branch that has some of the base Turborepo example code to help us get started. I have added those empty packages and made sure that everything was working correctly. You should be able to see the updated README on everything about the branch so far.
